package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// goFieldTargets maps Go field names (as generated by protoc-gen-go) to semantic
// types that replace the default numeric types (uint32, uint64, etc.) for type safety.
// Grouped by target type; comments list the proto message types containing each field.
var goFieldTargets = map[string]string{
	// → AbilityID
	"AbilityId":         "AbilityID", // AvailableAbility, AbilityData, UnitTypeData, UpgradeData, UnitOrder, ActionRawUnitCommand, ActionRawToggleAutocast, RequestQueryBuildingPlacement, ActionError, BuildItem, ActionToggleAutocast
	"RemapsToAbilityId": "AbilityID", // AbilityData

	// → UnitTypeID
	"UnitId":          "UnitTypeID", // UnitTypeData
	"UnitType":        "UnitTypeID", // DebugCreateUnit, PassengerUnit, Unit, UnitInfo
	"TechAlias":       "UnitTypeID", // UnitTypeData
	"UnitAlias":       "UnitTypeID", // UnitTypeData
	"TechRequirement": "UnitTypeID", // UnitTypeData
	"LeaderUnitType":  "UnitTypeID", // ControlGroup
	"UnitTypeId":      "UnitTypeID", // ResponseQueryAvailableAbilities

	// → UpgradeID
	"UpgradeId":  "UpgradeID", // UpgradeData
	"UpgradeIds": "UpgradeID", // PlayerRaw

	// → BuffID
	"BuffId":  "BuffID", // BuffData
	"BuffIds": "BuffID", // Unit

	// → EffectID
	"EffectId": "EffectID", // EffectData, Effect

	// → UnitTag
	"Tag":              "UnitTag", // PowerSource, PassengerUnit, Unit, DebugKillUnit
	"UnitTag":          "UnitTag", // DebugSetUnitValue, RequestQueryAvailableAbilities, ResponseQueryAvailableAbilities, ActionError
	"TargetUnitTag":    "UnitTag", // UnitOrder, ActionRawUnitCommand
	"UnitTags":         "UnitTag", // ActionRawUnitCommand, ActionRawToggleAutocast, ActionObserverCameraFollowUnits
	"PlacingUnitTag":   "UnitTag", // RequestQueryBuildingPlacement
	"AddOnTag":         "UnitTag", // Unit
	"EngagedTargetTag": "UnitTag", // Unit
	"DeadUnits":        "UnitTag", // Event

	// → PlayerID
	"Owner":            "PlayerID", // DebugCreateUnit, Unit
	"PlayerId":         "PlayerID", // ResponseJoinGame, ChatReceived, PlayerInfo, PlayerCommon, ActionObserverPlayerPerspective, ActionObserverCameraFollowPlayer, PlayerResult
	"ObservedPlayerId": "PlayerID", // RequestJoinGame, RequestStartReplay

	// → Alliance
	"PlayerRelative": "Alliance", // UnitInfo
}

// postProcessGeneratedFiles rewrites protoc output to replace primitive types
// with semantic types (AbilityID, UnitTag, etc.), fix enum naming, and strip
// protoimpl internals that are unnecessary with vtprotobuf.
func postProcessGeneratedFiles() {
	files, err := filepath.Glob(filepath.Join("api", "*.pb.go"))
	check(err)

	// First pass: rewrite types and strip internals, collecting enum renames.
	enumRenames := map[string]string{}
	for _, f := range files {
		content, err := os.ReadFile(f)
		check(err)
		text := string(content)
		original := text

		if strings.HasSuffix(f, "_vtproto.pb.go") {
			text = rewriteVtprotoTypes(text, goFieldTargets)
			text = stripVtprotoUnknownFields(text)
		} else {
			var renames map[string]string
			text, renames = rewritePbGoTypes(text, goFieldTargets)
			for k, v := range renames {
				enumRenames[k] = v
			}
			text = stripPbGoInternals(text)

			// Add Actions field to Unit struct (framework-only, not part of SC2 proto)
			unitStructRe := regexp.MustCompile(`(type Unit struct \{[^}]*)(})`)
			text = unitStructRe.ReplaceAllString(text,
				"${1}\tActions []*AvailableAbility // framework field, not serialized\n$2")
		}

		if text != original {
			check(os.WriteFile(f, []byte(text), 0644))
			fmt.Printf("Post-processed %s\n", f)
		}
	}

	// Second pass: apply enum renames across all .pb.go files (cross-file references).
	if len(enumRenames) > 0 {
		for _, f := range files {
			if strings.HasSuffix(f, "_vtproto.pb.go") {
				continue
			}
			content, err := os.ReadFile(f)
			check(err)
			text := string(content)
			original := text
			for oldName, newName := range enumRenames {
				text = strings.ReplaceAll(text, oldName, newName)
			}
			if text != original {
				check(os.WriteFile(f, []byte(text), 0644))
				fmt.Printf("Renamed enums in %s\n", f)
			}
		}
	}
}

// isNumericType returns true for Go numeric types that we want to replace with semantic types.
func isNumericType(t string) bool {
	base := strings.TrimPrefix(t, "[]")
	switch base {
	case "uint32", "uint64", "int32", "int64":
		return true
	}
	return false
}

// rewritePbGoTypes rewrites struct field types, getter return types, and
// collects double-prefix enum nil constants for renaming.
func rewritePbGoTypes(text string, targets map[string]string) (string, map[string]string) {
	for goField, target := range targets {
		// Rewrite struct field types.
		// Matches: \t<GoField>  <type>  `protobuf:
		fieldRe := regexp.MustCompile(
			`(\t` + regexp.QuoteMeta(goField) + `\s+)((?:\[\])?\w+)(\s+` + "`" + `protobuf:)`)
		text = fieldRe.ReplaceAllStringFunc(text, func(match string) string {
			groups := fieldRe.FindStringSubmatch(match)
			oldType := groups[2]
			if !isNumericType(oldType) {
				return match // don't rewrite bool, string, enum, message fields
			}
			newType := target
			if strings.HasPrefix(oldType, "[]") {
				newType = "[]" + target
			}
			return groups[1] + newType + groups[3]
		})

		// Rewrite getter return types.
		// Matches: func (x *Struct) Get<GoField>() <type> {
		getterRe := regexp.MustCompile(
			`(func \(x \*\w+\) Get` + regexp.QuoteMeta(goField) + `\(\) )((?:\[\])?\w+)( \{)`)
		text = getterRe.ReplaceAllStringFunc(text, func(match string) string {
			groups := getterRe.FindStringSubmatch(match)
			oldType := groups[2]
			if !isNumericType(oldType) {
				return match
			}
			newType := target
			if strings.HasPrefix(oldType, "[]") {
				newType = "[]" + target
			}
			return groups[1] + newType + groups[3]
		})
	}

	// Collect double-prefix enum nil constants for cross-file renaming.
	// protoc-gen-go generates Status_Status_nil for top-level enum Status with
	// value Status_nil. We rename to Status_nil for backward compat.
	enumRenames := map[string]string{}
	nilConstRe := regexp.MustCompile(`\t(\w+_nil)\s+(\w+)\s*=\s*0\b`)
	for _, match := range nilConstRe.FindAllStringSubmatch(text, -1) {
		constName := match[1]
		typeName := match[2]
		doublePrefix := typeName + "_" + typeName + "_nil"
		if constName == doublePrefix {
			enumRenames[constName] = typeName + "_nil"
		}
	}

	return text, enumRenames
}

// stripPbGoInternals strips state/sizeCache/unknownFields fields from structs
// and simplifies Reset() and ProtoReflect() to not use MessageStateOf.
func stripPbGoInternals(text string) string {
	// Strip struct fields
	stateRe := regexp.MustCompile(`\tstate\s+protoimpl\.MessageState[^\n]*\n`)
	text = stateRe.ReplaceAllString(text, "")

	unknownRe := regexp.MustCompile(`\tunknownFields\s+protoimpl\.UnknownFields\n`)
	text = unknownRe.ReplaceAllString(text, "")

	sizeCacheRe := regexp.MustCompile(`\tsizeCache\s+protoimpl\.SizeCache\n`)
	text = sizeCacheRe.ReplaceAllString(text, "")

	// Simplify Reset(): remove MessageStateOf lines after *x = Type{}
	resetRe := regexp.MustCompile(
		`\tmi := &file_\w+_proto_msgTypes\[\d+\]\n` +
			`\tms := protoimpl\.X\.MessageStateOf\(protoimpl\.Pointer\(x\)\)\n` +
			`\tms\.StoreMessageInfo\(mi\)\n`)
	text = resetRe.ReplaceAllString(text, "")

	// Simplify ProtoReflect(): replace cached MessageStateOf path with direct MessageOf
	protoReflectRe := regexp.MustCompile(
		`(func \(x \*\w+\) ProtoReflect\(\) protoreflect\.Message \{\n)` +
			`\tmi := &(file_\w+_proto_msgTypes\[\d+\])\n` +
			`\tif x != nil \{\n` +
			`\t\tms := protoimpl\.X\.MessageStateOf\(protoimpl\.Pointer\(x\)\)\n` +
			`\t\tif ms\.LoadMessageInfo\(\) == nil \{\n` +
			`\t\t\tms\.StoreMessageInfo\(mi\)\n` +
			`\t\t\}\n` +
			`\t\treturn ms\n` +
			`\t\}\n` +
			`\treturn mi\.MessageOf\(x\)\n` +
			`\}`)
	text = protoReflectRe.ReplaceAllString(text, "${1}\treturn ${2}.MessageOf(x)\n}")

	return text
}

// rewriteVtprotoTypes rewrites type casts in unmarshal code to use semantic types.
func rewriteVtprotoTypes(text string, targets map[string]string) string {
	lines := strings.Split(text, "\n")

	castRe := regexp.MustCompile(`(\w+)\(b&0x7F\)`)
	makeRe := regexp.MustCompile(`make\(\[\](\w+),`)

	for goField, target := range targets {
		// Find case blocks by the error message that identifies the field.
		errorPattern := `for field ` + goField + `"`
		for i, line := range lines {
			if !strings.Contains(line, errorPattern) {
				continue
			}

			// Find case block boundaries (walk backward to case start, forward to next case).
			caseStart := 0
			for j := i - 1; j >= 0; j-- {
				t := strings.TrimSpace(lines[j])
				if (strings.HasPrefix(t, "case ") && strings.HasSuffix(t, ":")) ||
					strings.HasPrefix(t, "func ") {
					caseStart = j + 1
					break
				}
			}
			caseEnd := len(lines)
			for j := i + 1; j < len(lines); j++ {
				t := strings.TrimSpace(lines[j])
				if (strings.HasPrefix(t, "case ") && strings.HasSuffix(t, ":")) ||
					strings.HasPrefix(t, "func ") {
					caseEnd = j
					break
				}
			}

			// Apply replacements within the case block.
			for j := caseStart; j < caseEnd; j++ {
				newLine := lines[j]
				trimmed := strings.TrimSpace(newLine)

				// m.GoField |= <type>(b&0x7F) << shift
				if strings.Contains(newLine, "m."+goField) && strings.Contains(newLine, "(b&0x7F)") {
					newLine = castRe.ReplaceAllString(newLine, target+"(b&0x7F)")
				}

				// var v <type> (repeated/oneof fields use a local variable)
				if strings.HasPrefix(trimmed, "var v ") && !strings.Contains(trimmed, "=") {
					indent := newLine[:len(newLine)-len(strings.TrimLeft(newLine, "\t "))]
					newLine = indent + "var v " + target
				}

				// v |= <type>(b&0x7F) << shift
				if strings.HasPrefix(trimmed, "v |=") && strings.Contains(newLine, "(b&0x7F)") {
					newLine = castRe.ReplaceAllString(newLine, target+"(b&0x7F)")
				}

				// make([]<type>, 0, elementCount)
				if strings.Contains(newLine, "m."+goField) && strings.Contains(newLine, "make([]") {
					newLine = makeRe.ReplaceAllString(newLine, "make([]"+target+",")
				}

				lines[j] = newLine
			}
		}
	}

	return strings.Join(lines, "\n")
}

// stripVtprotoUnknownFields removes all unknownFields references from vtproto
// marshal, size, and unmarshal code.
func stripVtprotoUnknownFields(text string) string {
	// Marshal: remove the unknownFields copy block
	marshalRe := regexp.MustCompile(
		`\tif m\.unknownFields != nil \{\n` +
			`\t\ti -= len\(m\.unknownFields\)\n` +
			`\t\tcopy\(dAtA\[i:\], m\.unknownFields\)\n` +
			`\t\}\n`)
	text = marshalRe.ReplaceAllString(text, "")

	// Size: remove the unknownFields length addition
	sizeRe := regexp.MustCompile(`\tn \+= len\(m\.unknownFields\)\n`)
	text = sizeRe.ReplaceAllString(text, "")

	// Unmarshal: remove the unknownFields append line
	unmarshalRe := regexp.MustCompile(`\t\t\tm\.unknownFields = append\(m\.unknownFields, dAtA\[iNdEx:iNdEx\+skippy\]\.\.\.\)\n`)
	text = unmarshalRe.ReplaceAllString(text, "")

	return text
}
