// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: common.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Race int32

const (
	Race_NoRace  Race = 0
	Race_Terran  Race = 1
	Race_Zerg    Race = 2
	Race_Protoss Race = 3
	Race_Random  Race = 4
)

// Enum value maps for Race.
var (
	Race_name = map[int32]string{
		0: "NoRace",
		1: "Terran",
		2: "Zerg",
		3: "Protoss",
		4: "Random",
	}
	Race_value = map[string]int32{
		"NoRace":  0,
		"Terran":  1,
		"Zerg":    2,
		"Protoss": 3,
		"Random":  4,
	}
)

func (x Race) Enum() *Race {
	p := new(Race)
	*p = x
	return p
}

func (x Race) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Race) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Race) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Race) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Race.Descriptor instead.
func (Race) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type AvailableAbility struct {
	AbilityId     AbilityID `protobuf:"varint,1,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`
	RequiresPoint bool      `protobuf:"varint,2,opt,name=requires_point,json=requiresPoint,proto3" json:"requires_point,omitempty"`
}

func (x *AvailableAbility) Reset() {
	*x = AvailableAbility{}
}

func (x *AvailableAbility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableAbility) ProtoMessage() {}

func (x *AvailableAbility) ProtoReflect() protoreflect.Message {
	return file_common_proto_msgTypes[0].MessageOf(x)
}

// Deprecated: Use AvailableAbility.ProtoReflect.Descriptor instead.
func (*AvailableAbility) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableAbility) GetAbilityId() AbilityID {
	if x != nil {
		return x.AbilityId
	}
	return 0
}

func (x *AvailableAbility) GetRequiresPoint() bool {
	if x != nil {
		return x.RequiresPoint
	}
	return false
}

type ImageData struct {
	BitsPerPixel int32    `protobuf:"varint,1,opt,name=bits_per_pixel,json=bitsPerPixel,proto3" json:"bits_per_pixel,omitempty"` // Number of bits per pixel; 8 bits for a byte etc.
	Size         *Size2DI `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`                                        // Dimension in pixels.
	Data         []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                        // Binary data; the size of this buffer in bytes is width * height * bits_per_pixel / 8.
}

func (x *ImageData) Reset() {
	*x = ImageData{}
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	return file_common_proto_msgTypes[1].MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ImageData) GetBitsPerPixel() int32 {
	if x != nil {
		return x.BitsPerPixel
	}
	return 0
}

func (x *ImageData) GetSize() *Size2DI {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *ImageData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Point on the screen/minimap (e.g., 0..64).
// Note: bottom left of the screen is 0, 0.
type PointI struct {
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *PointI) Reset() {
	*x = PointI{}
}

func (x *PointI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointI) ProtoMessage() {}

func (x *PointI) ProtoReflect() protoreflect.Message {
	return file_common_proto_msgTypes[2].MessageOf(x)
}

// Deprecated: Use PointI.ProtoReflect.Descriptor instead.
func (*PointI) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *PointI) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PointI) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Screen space rectangular area.
type RectangleI struct {
	P0 *PointI `protobuf:"bytes,1,opt,name=p0,proto3" json:"p0,omitempty"`
	P1 *PointI `protobuf:"bytes,2,opt,name=p1,proto3" json:"p1,omitempty"`
}

func (x *RectangleI) Reset() {
	*x = RectangleI{}
}

func (x *RectangleI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectangleI) ProtoMessage() {}

func (x *RectangleI) ProtoReflect() protoreflect.Message {
	return file_common_proto_msgTypes[3].MessageOf(x)
}

// Deprecated: Use RectangleI.ProtoReflect.Descriptor instead.
func (*RectangleI) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *RectangleI) GetP0() *PointI {
	if x != nil {
		return x.P0
	}
	return nil
}

func (x *RectangleI) GetP1() *PointI {
	if x != nil {
		return x.P1
	}
	return nil
}

// Point on the game board, 0..255.
// Note: bottom left of the screen is 0, 0.
type Point2D struct {
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point2D) Reset() {
	*x = Point2D{}
}

func (x *Point2D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point2D) ProtoMessage() {}

func (x *Point2D) ProtoReflect() protoreflect.Message {
	return file_common_proto_msgTypes[4].MessageOf(x)
}

// Deprecated: Use Point2D.ProtoReflect.Descriptor instead.
func (*Point2D) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *Point2D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point2D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Point on the game board, 0..255.
// Note: bottom left of the screen is 0, 0.
type Point struct {
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	return file_common_proto_msgTypes[5].MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *Point) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

// Screen dimensions.
type Size2DI struct {
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Size2DI) Reset() {
	*x = Size2DI{}
}

func (x *Size2DI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size2DI) ProtoMessage() {}

func (x *Size2DI) ProtoReflect() protoreflect.Message {
	return file_common_proto_msgTypes[6].MessageOf(x)
}

// Deprecated: Use Size2DI.ProtoReflect.Descriptor instead.
func (*Size2DI) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *Size2DI) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Size2DI) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x0eSC2APIProtocol\"X\n" +
	"\x10AvailableAbility\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId\x12%\n" +
	"\x0erequires_point\x18\x02 \x01(\bR\rrequiresPoint\"r\n" +
	"\tImageData\x12$\n" +
	"\x0ebits_per_pixel\x18\x01 \x01(\x05R\fbitsPerPixel\x12+\n" +
	"\x04size\x18\x02 \x01(\v2\x17.SC2APIProtocol.Size2DIR\x04size\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"$\n" +
	"\x06PointI\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\\\n" +
	"\n" +
	"RectangleI\x12&\n" +
	"\x02p0\x18\x01 \x01(\v2\x16.SC2APIProtocol.PointIR\x02p0\x12&\n" +
	"\x02p1\x18\x02 \x01(\v2\x16.SC2APIProtocol.PointIR\x02p1\"%\n" +
	"\aPoint2D\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"1\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"%\n" +
	"\aSize2DI\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y*A\n" +
	"\x04Race\x12\n" +
	"\n" +
	"\x06NoRace\x10\x00\x12\n" +
	"\n" +
	"\x06Terran\x10\x01\x12\b\n" +
	"\x04Zerg\x10\x02\x12\v\n" +
	"\aProtoss\x10\x03\x12\n" +
	"\n" +
	"\x06Random\x10\x04B#Z!github.com/chippydip/go-sc2ai/apib\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_goTypes = []any{
	(Race)(0),                // 0: SC2APIProtocol.Race
	(*AvailableAbility)(nil), // 1: SC2APIProtocol.AvailableAbility
	(*ImageData)(nil),        // 2: SC2APIProtocol.ImageData
	(*PointI)(nil),           // 3: SC2APIProtocol.PointI
	(*RectangleI)(nil),       // 4: SC2APIProtocol.RectangleI
	(*Point2D)(nil),          // 5: SC2APIProtocol.Point2D
	(*Point)(nil),            // 6: SC2APIProtocol.Point
	(*Size2DI)(nil),          // 7: SC2APIProtocol.Size2DI
}
var file_common_proto_depIdxs = []int32{
	7, // 0: SC2APIProtocol.ImageData.size:type_name -> SC2APIProtocol.Size2DI
	3, // 1: SC2APIProtocol.RectangleI.p0:type_name -> SC2APIProtocol.PointI
	3, // 2: SC2APIProtocol.RectangleI.p1:type_name -> SC2APIProtocol.PointI
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
