// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: query.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestQuery struct {
	Pathing                    []*RequestQueryPathing            `protobuf:"bytes,1,rep,name=pathing,proto3" json:"pathing,omitempty"`
	Abilities                  []*RequestQueryAvailableAbilities `protobuf:"bytes,2,rep,name=abilities,proto3" json:"abilities,omitempty"`
	Placements                 []*RequestQueryBuildingPlacement  `protobuf:"bytes,3,rep,name=placements,proto3" json:"placements,omitempty"`
	IgnoreResourceRequirements bool                              `protobuf:"varint,4,opt,name=ignore_resource_requirements,json=ignoreResourceRequirements,proto3" json:"ignore_resource_requirements,omitempty"` // Ignores requirements like food, minerals and so on.
}

func (x *RequestQuery) Reset() {
	*x = RequestQuery{}
}

func (x *RequestQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQuery) ProtoMessage() {}

func (x *RequestQuery) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[0].MessageOf(x)
}

// Deprecated: Use RequestQuery.ProtoReflect.Descriptor instead.
func (*RequestQuery) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *RequestQuery) GetPathing() []*RequestQueryPathing {
	if x != nil {
		return x.Pathing
	}
	return nil
}

func (x *RequestQuery) GetAbilities() []*RequestQueryAvailableAbilities {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *RequestQuery) GetPlacements() []*RequestQueryBuildingPlacement {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *RequestQuery) GetIgnoreResourceRequirements() bool {
	if x != nil {
		return x.IgnoreResourceRequirements
	}
	return false
}

type ResponseQuery struct {
	Pathing       []*ResponseQueryPathing            `protobuf:"bytes,1,rep,name=pathing,proto3" json:"pathing,omitempty"`
	Abilities     []*ResponseQueryAvailableAbilities `protobuf:"bytes,2,rep,name=abilities,proto3" json:"abilities,omitempty"`
	Placements    []*ResponseQueryBuildingPlacement  `protobuf:"bytes,3,rep,name=placements,proto3" json:"placements,omitempty"`
}

func (x *ResponseQuery) Reset() {
	*x = ResponseQuery{}
}

func (x *ResponseQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQuery) ProtoMessage() {}

func (x *ResponseQuery) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[1].MessageOf(x)
}

// Deprecated: Use ResponseQuery.ProtoReflect.Descriptor instead.
func (*ResponseQuery) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseQuery) GetPathing() []*ResponseQueryPathing {
	if x != nil {
		return x.Pathing
	}
	return nil
}

func (x *ResponseQuery) GetAbilities() []*ResponseQueryAvailableAbilities {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *ResponseQuery) GetPlacements() []*ResponseQueryBuildingPlacement {
	if x != nil {
		return x.Placements
	}
	return nil
}

// --------------------------------------------------------------------------------------------------
type RequestQueryPathing struct {
	// Types that are valid to be assigned to Start:
	//
	//	*RequestQueryPathing_StartPos
	//	*RequestQueryPathing_UnitTag
	Start         isRequestQueryPathing_Start `protobuf_oneof:"start"`
	EndPos        *Point2D                    `protobuf:"bytes,3,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
}

func (x *RequestQueryPathing) Reset() {
	*x = RequestQueryPathing{}
}

func (x *RequestQueryPathing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryPathing) ProtoMessage() {}

func (x *RequestQueryPathing) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[2].MessageOf(x)
}

// Deprecated: Use RequestQueryPathing.ProtoReflect.Descriptor instead.
func (*RequestQueryPathing) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *RequestQueryPathing) GetStart() isRequestQueryPathing_Start {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RequestQueryPathing) GetStartPos() *Point2D {
	if x != nil {
		if x, ok := x.Start.(*RequestQueryPathing_StartPos); ok {
			return x.StartPos
		}
	}
	return nil
}

func (x *RequestQueryPathing) GetUnitTag() UnitTag {
	if x != nil {
		if x, ok := x.Start.(*RequestQueryPathing_UnitTag); ok {
			return x.UnitTag
		}
	}
	return 0
}

func (x *RequestQueryPathing) GetEndPos() *Point2D {
	if x != nil {
		return x.EndPos
	}
	return nil
}

type isRequestQueryPathing_Start interface {
	isRequestQueryPathing_Start()
}

type RequestQueryPathing_StartPos struct {
	StartPos *Point2D `protobuf:"bytes,1,opt,name=start_pos,json=startPos,proto3,oneof"`
}

type RequestQueryPathing_UnitTag struct {
	UnitTag UnitTag `protobuf:"varint,2,opt,name=unit_tag,json=unitTag,proto3,oneof"`
}

func (*RequestQueryPathing_StartPos) isRequestQueryPathing_Start() {}

func (*RequestQueryPathing_UnitTag) isRequestQueryPathing_Start() {}

type ResponseQueryPathing struct {
	Distance      float32                `protobuf:"fixed32,1,opt,name=distance,proto3" json:"distance,omitempty"` // 0 if no path exists
}

func (x *ResponseQueryPathing) Reset() {
	*x = ResponseQueryPathing{}
}

func (x *ResponseQueryPathing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQueryPathing) ProtoMessage() {}

func (x *ResponseQueryPathing) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[3].MessageOf(x)
}

// Deprecated: Use ResponseQueryPathing.ProtoReflect.Descriptor instead.
func (*ResponseQueryPathing) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseQueryPathing) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

// --------------------------------------------------------------------------------------------------
type RequestQueryAvailableAbilities struct {
	UnitTag       UnitTag                 `protobuf:"varint,1,opt,name=unit_tag,json=unitTag,proto3" json:"unit_tag,omitempty"`
}

func (x *RequestQueryAvailableAbilities) Reset() {
	*x = RequestQueryAvailableAbilities{}
}

func (x *RequestQueryAvailableAbilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryAvailableAbilities) ProtoMessage() {}

func (x *RequestQueryAvailableAbilities) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[4].MessageOf(x)
}

// Deprecated: Use RequestQueryAvailableAbilities.ProtoReflect.Descriptor instead.
func (*RequestQueryAvailableAbilities) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *RequestQueryAvailableAbilities) GetUnitTag() UnitTag {
	if x != nil {
		return x.UnitTag
	}
	return 0
}

type ResponseQueryAvailableAbilities struct {
	Abilities     []*AvailableAbility    `protobuf:"bytes,1,rep,name=abilities,proto3" json:"abilities,omitempty"`
	UnitTag       UnitTag                 `protobuf:"varint,2,opt,name=unit_tag,json=unitTag,proto3" json:"unit_tag,omitempty"`
	UnitTypeId    UnitTypeID                 `protobuf:"varint,3,opt,name=unit_type_id,json=unitTypeId,proto3" json:"unit_type_id,omitempty"`
}

func (x *ResponseQueryAvailableAbilities) Reset() {
	*x = ResponseQueryAvailableAbilities{}
}

func (x *ResponseQueryAvailableAbilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQueryAvailableAbilities) ProtoMessage() {}

func (x *ResponseQueryAvailableAbilities) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[5].MessageOf(x)
}

// Deprecated: Use ResponseQueryAvailableAbilities.ProtoReflect.Descriptor instead.
func (*ResponseQueryAvailableAbilities) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseQueryAvailableAbilities) GetAbilities() []*AvailableAbility {
	if x != nil {
		return x.Abilities
	}
	return nil
}

func (x *ResponseQueryAvailableAbilities) GetUnitTag() UnitTag {
	if x != nil {
		return x.UnitTag
	}
	return 0
}

func (x *ResponseQueryAvailableAbilities) GetUnitTypeId() UnitTypeID {
	if x != nil {
		return x.UnitTypeId
	}
	return 0
}

// --------------------------------------------------------------------------------------------------
type RequestQueryBuildingPlacement struct {
	AbilityId      AbilityID                  `protobuf:"varint,1,opt,name=ability_id,json=abilityId,proto3" json:"ability_id,omitempty"`
	TargetPos      *Point2D               `protobuf:"bytes,2,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`
	PlacingUnitTag UnitTag                 `protobuf:"varint,3,opt,name=placing_unit_tag,json=placingUnitTag,proto3" json:"placing_unit_tag,omitempty"` // Not required
}

func (x *RequestQueryBuildingPlacement) Reset() {
	*x = RequestQueryBuildingPlacement{}
}

func (x *RequestQueryBuildingPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestQueryBuildingPlacement) ProtoMessage() {}

func (x *RequestQueryBuildingPlacement) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[6].MessageOf(x)
}

// Deprecated: Use RequestQueryBuildingPlacement.ProtoReflect.Descriptor instead.
func (*RequestQueryBuildingPlacement) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *RequestQueryBuildingPlacement) GetAbilityId() AbilityID {
	if x != nil {
		return x.AbilityId
	}
	return 0
}

func (x *RequestQueryBuildingPlacement) GetTargetPos() *Point2D {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *RequestQueryBuildingPlacement) GetPlacingUnitTag() UnitTag {
	if x != nil {
		return x.PlacingUnitTag
	}
	return 0
}

type ResponseQueryBuildingPlacement struct {
	Result        ActionResult           `protobuf:"varint,1,opt,name=result,proto3,enum=SC2APIProtocol.ActionResult" json:"result,omitempty"`
}

func (x *ResponseQueryBuildingPlacement) Reset() {
	*x = ResponseQueryBuildingPlacement{}
}

func (x *ResponseQueryBuildingPlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseQueryBuildingPlacement) ProtoMessage() {}

func (x *ResponseQueryBuildingPlacement) ProtoReflect() protoreflect.Message {
	return file_query_proto_msgTypes[7].MessageOf(x)
}

// Deprecated: Use ResponseQueryBuildingPlacement.ProtoReflect.Descriptor instead.
func (*ResponseQueryBuildingPlacement) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseQueryBuildingPlacement) GetResult() ActionResult {
	if x != nil {
		return x.Result
	}
	return ActionResult_nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x0eSC2APIProtocol\x1a\fcommon.proto\x1a\verror.proto\"\xac\x02\n" +
	"\fRequestQuery\x12=\n" +
	"\apathing\x18\x01 \x03(\v2#.SC2APIProtocol.RequestQueryPathingR\apathing\x12L\n" +
	"\tabilities\x18\x02 \x03(\v2..SC2APIProtocol.RequestQueryAvailableAbilitiesR\tabilities\x12M\n" +
	"\n" +
	"placements\x18\x03 \x03(\v2-.SC2APIProtocol.RequestQueryBuildingPlacementR\n" +
	"placements\x12@\n" +
	"\x1cignore_resource_requirements\x18\x04 \x01(\bR\x1aignoreResourceRequirements\"\xee\x01\n" +
	"\rResponseQuery\x12>\n" +
	"\apathing\x18\x01 \x03(\v2$.SC2APIProtocol.ResponseQueryPathingR\apathing\x12M\n" +
	"\tabilities\x18\x02 \x03(\v2/.SC2APIProtocol.ResponseQueryAvailableAbilitiesR\tabilities\x12N\n" +
	"\n" +
	"placements\x18\x03 \x03(\v2..SC2APIProtocol.ResponseQueryBuildingPlacementR\n" +
	"placements\"\xa5\x01\n" +
	"\x13RequestQueryPathing\x126\n" +
	"\tstart_pos\x18\x01 \x01(\v2\x17.SC2APIProtocol.Point2DH\x00R\bstartPos\x12\x1b\n" +
	"\bunit_tag\x18\x02 \x01(\x04H\x00R\aunitTag\x120\n" +
	"\aend_pos\x18\x03 \x01(\v2\x17.SC2APIProtocol.Point2DR\x06endPosB\a\n" +
	"\x05start\"2\n" +
	"\x14ResponseQueryPathing\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x02R\bdistance\";\n" +
	"\x1eRequestQueryAvailableAbilities\x12\x19\n" +
	"\bunit_tag\x18\x01 \x01(\x04R\aunitTag\"\x9e\x01\n" +
	"\x1fResponseQueryAvailableAbilities\x12>\n" +
	"\tabilities\x18\x01 \x03(\v2 .SC2APIProtocol.AvailableAbilityR\tabilities\x12\x19\n" +
	"\bunit_tag\x18\x02 \x01(\x04R\aunitTag\x12 \n" +
	"\funit_type_id\x18\x03 \x01(\rR\n" +
	"unitTypeId\"\xa0\x01\n" +
	"\x1dRequestQueryBuildingPlacement\x12\x1d\n" +
	"\n" +
	"ability_id\x18\x01 \x01(\x05R\tabilityId\x126\n" +
	"\n" +
	"target_pos\x18\x02 \x01(\v2\x17.SC2APIProtocol.Point2DR\ttargetPos\x12(\n" +
	"\x10placing_unit_tag\x18\x03 \x01(\x04R\x0eplacingUnitTag\"V\n" +
	"\x1eResponseQueryBuildingPlacement\x124\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1c.SC2APIProtocol.ActionResultR\x06resultB#Z!github.com/chippydip/go-sc2ai/apib\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_query_proto_goTypes = []any{
	(*RequestQuery)(nil),                    // 0: SC2APIProtocol.RequestQuery
	(*ResponseQuery)(nil),                   // 1: SC2APIProtocol.ResponseQuery
	(*RequestQueryPathing)(nil),             // 2: SC2APIProtocol.RequestQueryPathing
	(*ResponseQueryPathing)(nil),            // 3: SC2APIProtocol.ResponseQueryPathing
	(*RequestQueryAvailableAbilities)(nil),  // 4: SC2APIProtocol.RequestQueryAvailableAbilities
	(*ResponseQueryAvailableAbilities)(nil), // 5: SC2APIProtocol.ResponseQueryAvailableAbilities
	(*RequestQueryBuildingPlacement)(nil),   // 6: SC2APIProtocol.RequestQueryBuildingPlacement
	(*ResponseQueryBuildingPlacement)(nil),  // 7: SC2APIProtocol.ResponseQueryBuildingPlacement
	(*Point2D)(nil),                         // 8: SC2APIProtocol.Point2D
	(*AvailableAbility)(nil),                // 9: SC2APIProtocol.AvailableAbility
	(ActionResult)(0),                       // 10: SC2APIProtocol.ActionResult
}
var file_query_proto_depIdxs = []int32{
	2,  // 0: SC2APIProtocol.RequestQuery.pathing:type_name -> SC2APIProtocol.RequestQueryPathing
	4,  // 1: SC2APIProtocol.RequestQuery.abilities:type_name -> SC2APIProtocol.RequestQueryAvailableAbilities
	6,  // 2: SC2APIProtocol.RequestQuery.placements:type_name -> SC2APIProtocol.RequestQueryBuildingPlacement
	3,  // 3: SC2APIProtocol.ResponseQuery.pathing:type_name -> SC2APIProtocol.ResponseQueryPathing
	5,  // 4: SC2APIProtocol.ResponseQuery.abilities:type_name -> SC2APIProtocol.ResponseQueryAvailableAbilities
	7,  // 5: SC2APIProtocol.ResponseQuery.placements:type_name -> SC2APIProtocol.ResponseQueryBuildingPlacement
	8,  // 6: SC2APIProtocol.RequestQueryPathing.start_pos:type_name -> SC2APIProtocol.Point2D
	8,  // 7: SC2APIProtocol.RequestQueryPathing.end_pos:type_name -> SC2APIProtocol.Point2D
	9,  // 8: SC2APIProtocol.ResponseQueryAvailableAbilities.abilities:type_name -> SC2APIProtocol.AvailableAbility
	8,  // 9: SC2APIProtocol.RequestQueryBuildingPlacement.target_pos:type_name -> SC2APIProtocol.Point2D
	10, // 10: SC2APIProtocol.ResponseQueryBuildingPlacement.result:type_name -> SC2APIProtocol.ActionResult
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_common_proto_init()
	file_error_proto_init()
	file_query_proto_msgTypes[2].OneofWrappers = []any{
		(*RequestQueryPathing_StartPos)(nil),
		(*RequestQueryPathing_UnitTag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
