// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: score.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Score_ScoreType int32

const (
	Score_ScoreType_nil Score_ScoreType = 0
	Score_Curriculum    Score_ScoreType = 1 // map generated score (from curriculum maps with special scoring)
	Score_Melee         Score_ScoreType = 2 // summation of in-progress and current units/buildings value + minerals + vespene
)

// Enum value maps for Score_ScoreType.
var (
	Score_ScoreType_name = map[int32]string{
		0: "ScoreType_nil",
		1: "Curriculum",
		2: "Melee",
	}
	Score_ScoreType_value = map[string]int32{
		"ScoreType_nil": 0,
		"Curriculum":    1,
		"Melee":         2,
	}
)

func (x Score_ScoreType) Enum() *Score_ScoreType {
	p := new(Score_ScoreType)
	*p = x
	return p
}

func (x Score_ScoreType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Score_ScoreType) Descriptor() protoreflect.EnumDescriptor {
	return file_score_proto_enumTypes[0].Descriptor()
}

func (Score_ScoreType) Type() protoreflect.EnumType {
	return &file_score_proto_enumTypes[0]
}

func (x Score_ScoreType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Score_ScoreType.Descriptor instead.
func (Score_ScoreType) EnumDescriptor() ([]byte, []int) {
	return file_score_proto_rawDescGZIP(), []int{0, 0}
}

type Score struct {
	ScoreType    Score_ScoreType `protobuf:"varint,6,opt,name=score_type,json=scoreType,proto3,enum=SC2APIProtocol.Score_ScoreType" json:"score_type,omitempty"`
	Score        int32           `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"` // Note: check score_type to know whether this is a melee score or curriculum score
	ScoreDetails *ScoreDetails   `protobuf:"bytes,8,opt,name=score_details,json=scoreDetails,proto3" json:"score_details,omitempty"`
}

func (x *Score) Reset() {
	*x = Score{}
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	return file_score_proto_msgTypes[0].MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_score_proto_rawDescGZIP(), []int{0}
}

func (x *Score) GetScoreType() Score_ScoreType {
	if x != nil {
		return x.ScoreType
	}
	return Score_ScoreType_nil
}

func (x *Score) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Score) GetScoreDetails() *ScoreDetails {
	if x != nil {
		return x.ScoreDetails
	}
	return nil
}

type CategoryScoreDetails struct {
	None       float32 `protobuf:"fixed32,1,opt,name=none,proto3" json:"none,omitempty"` // Used when no other category is configured in game data
	Army       float32 `protobuf:"fixed32,2,opt,name=army,proto3" json:"army,omitempty"`
	Economy    float32 `protobuf:"fixed32,3,opt,name=economy,proto3" json:"economy,omitempty"`
	Technology float32 `protobuf:"fixed32,4,opt,name=technology,proto3" json:"technology,omitempty"`
	Upgrade    float32 `protobuf:"fixed32,5,opt,name=upgrade,proto3" json:"upgrade,omitempty"`
}

func (x *CategoryScoreDetails) Reset() {
	*x = CategoryScoreDetails{}
}

func (x *CategoryScoreDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryScoreDetails) ProtoMessage() {}

func (x *CategoryScoreDetails) ProtoReflect() protoreflect.Message {
	return file_score_proto_msgTypes[1].MessageOf(x)
}

// Deprecated: Use CategoryScoreDetails.ProtoReflect.Descriptor instead.
func (*CategoryScoreDetails) Descriptor() ([]byte, []int) {
	return file_score_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryScoreDetails) GetNone() float32 {
	if x != nil {
		return x.None
	}
	return 0
}

func (x *CategoryScoreDetails) GetArmy() float32 {
	if x != nil {
		return x.Army
	}
	return 0
}

func (x *CategoryScoreDetails) GetEconomy() float32 {
	if x != nil {
		return x.Economy
	}
	return 0
}

func (x *CategoryScoreDetails) GetTechnology() float32 {
	if x != nil {
		return x.Technology
	}
	return 0
}

func (x *CategoryScoreDetails) GetUpgrade() float32 {
	if x != nil {
		return x.Upgrade
	}
	return 0
}

type VitalScoreDetails struct {
	Life    float32 `protobuf:"fixed32,1,opt,name=life,proto3" json:"life,omitempty"`
	Shields float32 `protobuf:"fixed32,2,opt,name=shields,proto3" json:"shields,omitempty"`
	Energy  float32 `protobuf:"fixed32,3,opt,name=energy,proto3" json:"energy,omitempty"`
}

func (x *VitalScoreDetails) Reset() {
	*x = VitalScoreDetails{}
}

func (x *VitalScoreDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VitalScoreDetails) ProtoMessage() {}

func (x *VitalScoreDetails) ProtoReflect() protoreflect.Message {
	return file_score_proto_msgTypes[2].MessageOf(x)
}

// Deprecated: Use VitalScoreDetails.ProtoReflect.Descriptor instead.
func (*VitalScoreDetails) Descriptor() ([]byte, []int) {
	return file_score_proto_rawDescGZIP(), []int{2}
}

func (x *VitalScoreDetails) GetLife() float32 {
	if x != nil {
		return x.Life
	}
	return 0
}

func (x *VitalScoreDetails) GetShields() float32 {
	if x != nil {
		return x.Shields
	}
	return 0
}

func (x *VitalScoreDetails) GetEnergy() float32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

type ScoreDetails struct {
	// Sum of time any available structure able to produce a unit is not. The time stacks, as in, three idle barracks will increase idle_production_time three times quicker than just one.
	IdleProductionTime float32 `protobuf:"fixed32,1,opt,name=idle_production_time,json=idleProductionTime,proto3" json:"idle_production_time,omitempty"`
	// Sum of time any worker is not mining. Note a worker building is not idle and three idle workers will increase this value three times quicker than just one.
	IdleWorkerTime float32 `protobuf:"fixed32,2,opt,name=idle_worker_time,json=idleWorkerTime,proto3" json:"idle_worker_time,omitempty"`
	// Sum of minerals and vespene spent on completed units.
	TotalValueUnits float32 `protobuf:"fixed32,3,opt,name=total_value_units,json=totalValueUnits,proto3" json:"total_value_units,omitempty"`
	// Sum of minerals and vespene spent on completed structures.
	TotalValueStructures float32 `protobuf:"fixed32,4,opt,name=total_value_structures,json=totalValueStructures,proto3" json:"total_value_structures,omitempty"`
	// Sum of minerals and vespene of units, belonging to the opponent, that the player has destroyed.
	KilledValueUnits float32 `protobuf:"fixed32,5,opt,name=killed_value_units,json=killedValueUnits,proto3" json:"killed_value_units,omitempty"`
	// Sum of minerals and vespene of structures, belonging to the opponent, that the player has destroyed.
	KilledValueStructures float32 `protobuf:"fixed32,6,opt,name=killed_value_structures,json=killedValueStructures,proto3" json:"killed_value_structures,omitempty"`
	// Sum of minerals collected by the player.
	CollectedMinerals float32 `protobuf:"fixed32,7,opt,name=collected_minerals,json=collectedMinerals,proto3" json:"collected_minerals,omitempty"`
	// Sum of vespene collected by the player.
	CollectedVespene float32 `protobuf:"fixed32,8,opt,name=collected_vespene,json=collectedVespene,proto3" json:"collected_vespene,omitempty"`
	// Estimated income of minerals over the next minute based on the players current income. The unit is minerals per minute.
	CollectionRateMinerals float32 `protobuf:"fixed32,9,opt,name=collection_rate_minerals,json=collectionRateMinerals,proto3" json:"collection_rate_minerals,omitempty"`
	// Estimated income of vespene over the next minute based on the players current income. The unit is vespene per minute.
	CollectionRateVespene float32 `protobuf:"fixed32,10,opt,name=collection_rate_vespene,json=collectionRateVespene,proto3" json:"collection_rate_vespene,omitempty"`
	// Sum of spent minerals at the moment it is spent. For example, this number is incremented by 50 the moment an scv is queued in a command center.  It is decremented by 50 if that unit is canceled.
	SpentMinerals float32 `protobuf:"fixed32,11,opt,name=spent_minerals,json=spentMinerals,proto3" json:"spent_minerals,omitempty"`
	// Sum of spent vespene at the moment it is spent. For example, this number is incremented by 50 when a reaper is queued but decremented by 50 if it is canceled.
	SpentVespene float32 `protobuf:"fixed32,12,opt,name=spent_vespene,json=spentVespene,proto3" json:"spent_vespene,omitempty"`
	// Sum of food, or supply, utilized in the categories above.
	FoodUsed *CategoryScoreDetails `protobuf:"bytes,13,opt,name=food_used,json=foodUsed,proto3" json:"food_used,omitempty"`
	// Sum of enemies catagories destroyed in minerals.
	KilledMinerals *CategoryScoreDetails `protobuf:"bytes,14,opt,name=killed_minerals,json=killedMinerals,proto3" json:"killed_minerals,omitempty"`
	// Sum of enemies catagories destroyed in vespene.
	KilledVespene *CategoryScoreDetails `protobuf:"bytes,15,opt,name=killed_vespene,json=killedVespene,proto3" json:"killed_vespene,omitempty"`
	// Sum of lost minerals for the player in each category.
	LostMinerals *CategoryScoreDetails `protobuf:"bytes,16,opt,name=lost_minerals,json=lostMinerals,proto3" json:"lost_minerals,omitempty"`
	// Sum of lost vespene for the player in each category.
	LostVespene *CategoryScoreDetails `protobuf:"bytes,17,opt,name=lost_vespene,json=lostVespene,proto3" json:"lost_vespene,omitempty"`
	// Sum of the lost minerals via destroying the players own units/buildings.
	FriendlyFireMinerals *CategoryScoreDetails `protobuf:"bytes,18,opt,name=friendly_fire_minerals,json=friendlyFireMinerals,proto3" json:"friendly_fire_minerals,omitempty"`
	// Sum of the lost vespene via destroying the players own units/buildings.
	FriendlyFireVespene *CategoryScoreDetails `protobuf:"bytes,19,opt,name=friendly_fire_vespene,json=friendlyFireVespene,proto3" json:"friendly_fire_vespene,omitempty"`
	// Sum of used minerals for the player in each category for each existing unit or upgrade. Therefore if a unit died worth 50 mierals this number will be decremented by 50.
	UsedMinerals *CategoryScoreDetails `protobuf:"bytes,20,opt,name=used_minerals,json=usedMinerals,proto3" json:"used_minerals,omitempty"`
	// Sum of used vespene for the player in each category. Therefore if a unit died worth 50 vespene this number will be decremented by 50.
	UsedVespene *CategoryScoreDetails `protobuf:"bytes,21,opt,name=used_vespene,json=usedVespene,proto3" json:"used_vespene,omitempty"`
	// Sum of used minerals throughout the entire game for each category. Unliked used_minerals, this value is never decremented.
	TotalUsedMinerals *CategoryScoreDetails `protobuf:"bytes,22,opt,name=total_used_minerals,json=totalUsedMinerals,proto3" json:"total_used_minerals,omitempty"`
	// Sum of used vespene throughout the entire game for each category. Unliked used_vespene, this value is never decremented.
	TotalUsedVespene *CategoryScoreDetails `protobuf:"bytes,23,opt,name=total_used_vespene,json=totalUsedVespene,proto3" json:"total_used_vespene,omitempty"`
	// Sum of damage dealt to the player's opponent for each category.
	TotalDamageDealt *VitalScoreDetails `protobuf:"bytes,24,opt,name=total_damage_dealt,json=totalDamageDealt,proto3" json:"total_damage_dealt,omitempty"`
	// Sum of damage taken by the player for each category.
	TotalDamageTaken *VitalScoreDetails `protobuf:"bytes,25,opt,name=total_damage_taken,json=totalDamageTaken,proto3" json:"total_damage_taken,omitempty"`
	// Sum of health healed by the player. Note that technology can be healed (by queens) or repaired (by scvs).
	TotalHealed *VitalScoreDetails `protobuf:"bytes,26,opt,name=total_healed,json=totalHealed,proto3" json:"total_healed,omitempty"`
	// Recent raw APM.
	CurrentApm float32 `protobuf:"fixed32,27,opt,name=current_apm,json=currentApm,proto3" json:"current_apm,omitempty"`
	// Recent effective APM.
	CurrentEffectiveApm float32 `protobuf:"fixed32,28,opt,name=current_effective_apm,json=currentEffectiveApm,proto3" json:"current_effective_apm,omitempty"`
}

func (x *ScoreDetails) Reset() {
	*x = ScoreDetails{}
}

func (x *ScoreDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreDetails) ProtoMessage() {}

func (x *ScoreDetails) ProtoReflect() protoreflect.Message {
	return file_score_proto_msgTypes[3].MessageOf(x)
}

// Deprecated: Use ScoreDetails.ProtoReflect.Descriptor instead.
func (*ScoreDetails) Descriptor() ([]byte, []int) {
	return file_score_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreDetails) GetIdleProductionTime() float32 {
	if x != nil {
		return x.IdleProductionTime
	}
	return 0
}

func (x *ScoreDetails) GetIdleWorkerTime() float32 {
	if x != nil {
		return x.IdleWorkerTime
	}
	return 0
}

func (x *ScoreDetails) GetTotalValueUnits() float32 {
	if x != nil {
		return x.TotalValueUnits
	}
	return 0
}

func (x *ScoreDetails) GetTotalValueStructures() float32 {
	if x != nil {
		return x.TotalValueStructures
	}
	return 0
}

func (x *ScoreDetails) GetKilledValueUnits() float32 {
	if x != nil {
		return x.KilledValueUnits
	}
	return 0
}

func (x *ScoreDetails) GetKilledValueStructures() float32 {
	if x != nil {
		return x.KilledValueStructures
	}
	return 0
}

func (x *ScoreDetails) GetCollectedMinerals() float32 {
	if x != nil {
		return x.CollectedMinerals
	}
	return 0
}

func (x *ScoreDetails) GetCollectedVespene() float32 {
	if x != nil {
		return x.CollectedVespene
	}
	return 0
}

func (x *ScoreDetails) GetCollectionRateMinerals() float32 {
	if x != nil {
		return x.CollectionRateMinerals
	}
	return 0
}

func (x *ScoreDetails) GetCollectionRateVespene() float32 {
	if x != nil {
		return x.CollectionRateVespene
	}
	return 0
}

func (x *ScoreDetails) GetSpentMinerals() float32 {
	if x != nil {
		return x.SpentMinerals
	}
	return 0
}

func (x *ScoreDetails) GetSpentVespene() float32 {
	if x != nil {
		return x.SpentVespene
	}
	return 0
}

func (x *ScoreDetails) GetFoodUsed() *CategoryScoreDetails {
	if x != nil {
		return x.FoodUsed
	}
	return nil
}

func (x *ScoreDetails) GetKilledMinerals() *CategoryScoreDetails {
	if x != nil {
		return x.KilledMinerals
	}
	return nil
}

func (x *ScoreDetails) GetKilledVespene() *CategoryScoreDetails {
	if x != nil {
		return x.KilledVespene
	}
	return nil
}

func (x *ScoreDetails) GetLostMinerals() *CategoryScoreDetails {
	if x != nil {
		return x.LostMinerals
	}
	return nil
}

func (x *ScoreDetails) GetLostVespene() *CategoryScoreDetails {
	if x != nil {
		return x.LostVespene
	}
	return nil
}

func (x *ScoreDetails) GetFriendlyFireMinerals() *CategoryScoreDetails {
	if x != nil {
		return x.FriendlyFireMinerals
	}
	return nil
}

func (x *ScoreDetails) GetFriendlyFireVespene() *CategoryScoreDetails {
	if x != nil {
		return x.FriendlyFireVespene
	}
	return nil
}

func (x *ScoreDetails) GetUsedMinerals() *CategoryScoreDetails {
	if x != nil {
		return x.UsedMinerals
	}
	return nil
}

func (x *ScoreDetails) GetUsedVespene() *CategoryScoreDetails {
	if x != nil {
		return x.UsedVespene
	}
	return nil
}

func (x *ScoreDetails) GetTotalUsedMinerals() *CategoryScoreDetails {
	if x != nil {
		return x.TotalUsedMinerals
	}
	return nil
}

func (x *ScoreDetails) GetTotalUsedVespene() *CategoryScoreDetails {
	if x != nil {
		return x.TotalUsedVespene
	}
	return nil
}

func (x *ScoreDetails) GetTotalDamageDealt() *VitalScoreDetails {
	if x != nil {
		return x.TotalDamageDealt
	}
	return nil
}

func (x *ScoreDetails) GetTotalDamageTaken() *VitalScoreDetails {
	if x != nil {
		return x.TotalDamageTaken
	}
	return nil
}

func (x *ScoreDetails) GetTotalHealed() *VitalScoreDetails {
	if x != nil {
		return x.TotalHealed
	}
	return nil
}

func (x *ScoreDetails) GetCurrentApm() float32 {
	if x != nil {
		return x.CurrentApm
	}
	return 0
}

func (x *ScoreDetails) GetCurrentEffectiveApm() float32 {
	if x != nil {
		return x.CurrentEffectiveApm
	}
	return 0
}

var File_score_proto protoreflect.FileDescriptor

const file_score_proto_rawDesc = "" +
	"\n" +
	"\vscore.proto\x12\x0eSC2APIProtocol\"\xdb\x01\n" +
	"\x05Score\x12>\n" +
	"\n" +
	"score_type\x18\x06 \x01(\x0e2\x1f.SC2APIProtocol.Score.ScoreTypeR\tscoreType\x12\x14\n" +
	"\x05score\x18\a \x01(\x05R\x05score\x12A\n" +
	"\rscore_details\x18\b \x01(\v2\x1c.SC2APIProtocol.ScoreDetailsR\fscoreDetails\"9\n" +
	"\tScoreType\x12\x11\n" +
	"\rScoreType_nil\x10\x00\x12\x0e\n" +
	"\n" +
	"Curriculum\x10\x01\x12\t\n" +
	"\x05Melee\x10\x02\"\x92\x01\n" +
	"\x14CategoryScoreDetails\x12\x12\n" +
	"\x04none\x18\x01 \x01(\x02R\x04none\x12\x12\n" +
	"\x04army\x18\x02 \x01(\x02R\x04army\x12\x18\n" +
	"\aeconomy\x18\x03 \x01(\x02R\aeconomy\x12\x1e\n" +
	"\n" +
	"technology\x18\x04 \x01(\x02R\n" +
	"technology\x12\x18\n" +
	"\aupgrade\x18\x05 \x01(\x02R\aupgrade\"Y\n" +
	"\x11VitalScoreDetails\x12\x12\n" +
	"\x04life\x18\x01 \x01(\x02R\x04life\x12\x18\n" +
	"\ashields\x18\x02 \x01(\x02R\ashields\x12\x16\n" +
	"\x06energy\x18\x03 \x01(\x02R\x06energy\"\xf0\r\n" +
	"\fScoreDetails\x120\n" +
	"\x14idle_production_time\x18\x01 \x01(\x02R\x12idleProductionTime\x12(\n" +
	"\x10idle_worker_time\x18\x02 \x01(\x02R\x0eidleWorkerTime\x12*\n" +
	"\x11total_value_units\x18\x03 \x01(\x02R\x0ftotalValueUnits\x124\n" +
	"\x16total_value_structures\x18\x04 \x01(\x02R\x14totalValueStructures\x12,\n" +
	"\x12killed_value_units\x18\x05 \x01(\x02R\x10killedValueUnits\x126\n" +
	"\x17killed_value_structures\x18\x06 \x01(\x02R\x15killedValueStructures\x12-\n" +
	"\x12collected_minerals\x18\a \x01(\x02R\x11collectedMinerals\x12+\n" +
	"\x11collected_vespene\x18\b \x01(\x02R\x10collectedVespene\x128\n" +
	"\x18collection_rate_minerals\x18\t \x01(\x02R\x16collectionRateMinerals\x126\n" +
	"\x17collection_rate_vespene\x18\n" +
	" \x01(\x02R\x15collectionRateVespene\x12%\n" +
	"\x0espent_minerals\x18\v \x01(\x02R\rspentMinerals\x12#\n" +
	"\rspent_vespene\x18\f \x01(\x02R\fspentVespene\x12A\n" +
	"\tfood_used\x18\r \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\bfoodUsed\x12M\n" +
	"\x0fkilled_minerals\x18\x0e \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\x0ekilledMinerals\x12K\n" +
	"\x0ekilled_vespene\x18\x0f \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\rkilledVespene\x12I\n" +
	"\rlost_minerals\x18\x10 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\flostMinerals\x12G\n" +
	"\flost_vespene\x18\x11 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\vlostVespene\x12Z\n" +
	"\x16friendly_fire_minerals\x18\x12 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\x14friendlyFireMinerals\x12X\n" +
	"\x15friendly_fire_vespene\x18\x13 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\x13friendlyFireVespene\x12I\n" +
	"\rused_minerals\x18\x14 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\fusedMinerals\x12G\n" +
	"\fused_vespene\x18\x15 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\vusedVespene\x12T\n" +
	"\x13total_used_minerals\x18\x16 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\x11totalUsedMinerals\x12R\n" +
	"\x12total_used_vespene\x18\x17 \x01(\v2$.SC2APIProtocol.CategoryScoreDetailsR\x10totalUsedVespene\x12O\n" +
	"\x12total_damage_dealt\x18\x18 \x01(\v2!.SC2APIProtocol.VitalScoreDetailsR\x10totalDamageDealt\x12O\n" +
	"\x12total_damage_taken\x18\x19 \x01(\v2!.SC2APIProtocol.VitalScoreDetailsR\x10totalDamageTaken\x12D\n" +
	"\ftotal_healed\x18\x1a \x01(\v2!.SC2APIProtocol.VitalScoreDetailsR\vtotalHealed\x12\x1f\n" +
	"\vcurrent_apm\x18\x1b \x01(\x02R\n" +
	"currentApm\x122\n" +
	"\x15current_effective_apm\x18\x1c \x01(\x02R\x13currentEffectiveApmB#Z!github.com/chippydip/go-sc2ai/apib\x06proto3"

var (
	file_score_proto_rawDescOnce sync.Once
	file_score_proto_rawDescData []byte
)

func file_score_proto_rawDescGZIP() []byte {
	file_score_proto_rawDescOnce.Do(func() {
		file_score_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_score_proto_rawDesc), len(file_score_proto_rawDesc)))
	})
	return file_score_proto_rawDescData
}

var file_score_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_score_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_score_proto_goTypes = []any{
	(Score_ScoreType)(0),         // 0: SC2APIProtocol.Score.ScoreType
	(*Score)(nil),                // 1: SC2APIProtocol.Score
	(*CategoryScoreDetails)(nil), // 2: SC2APIProtocol.CategoryScoreDetails
	(*VitalScoreDetails)(nil),    // 3: SC2APIProtocol.VitalScoreDetails
	(*ScoreDetails)(nil),         // 4: SC2APIProtocol.ScoreDetails
}
var file_score_proto_depIdxs = []int32{
	0,  // 0: SC2APIProtocol.Score.score_type:type_name -> SC2APIProtocol.Score.ScoreType
	4,  // 1: SC2APIProtocol.Score.score_details:type_name -> SC2APIProtocol.ScoreDetails
	2,  // 2: SC2APIProtocol.ScoreDetails.food_used:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 3: SC2APIProtocol.ScoreDetails.killed_minerals:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 4: SC2APIProtocol.ScoreDetails.killed_vespene:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 5: SC2APIProtocol.ScoreDetails.lost_minerals:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 6: SC2APIProtocol.ScoreDetails.lost_vespene:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 7: SC2APIProtocol.ScoreDetails.friendly_fire_minerals:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 8: SC2APIProtocol.ScoreDetails.friendly_fire_vespene:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 9: SC2APIProtocol.ScoreDetails.used_minerals:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 10: SC2APIProtocol.ScoreDetails.used_vespene:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 11: SC2APIProtocol.ScoreDetails.total_used_minerals:type_name -> SC2APIProtocol.CategoryScoreDetails
	2,  // 12: SC2APIProtocol.ScoreDetails.total_used_vespene:type_name -> SC2APIProtocol.CategoryScoreDetails
	3,  // 13: SC2APIProtocol.ScoreDetails.total_damage_dealt:type_name -> SC2APIProtocol.VitalScoreDetails
	3,  // 14: SC2APIProtocol.ScoreDetails.total_damage_taken:type_name -> SC2APIProtocol.VitalScoreDetails
	3,  // 15: SC2APIProtocol.ScoreDetails.total_healed:type_name -> SC2APIProtocol.VitalScoreDetails
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_score_proto_init() }
func file_score_proto_init() {
	if File_score_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_score_proto_rawDesc), len(file_score_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_score_proto_goTypes,
		DependencyIndexes: file_score_proto_depIdxs,
		EnumInfos:         file_score_proto_enumTypes,
		MessageInfos:      file_score_proto_msgTypes,
	}.Build()
	File_score_proto = out.File
	file_score_proto_goTypes = nil
	file_score_proto_depIdxs = nil
}
